# Generated by Django 2.2.4 on 2019-09-21 11:40

from django.db import migrations, models
import django.db.models.deletion
import messaging.models
import messaging.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=27, unique=True)),
                ('image', models.ImageField(upload_to=messaging.models.get_image_name)),
                ('thumbnail', models.ImageField(upload_to=messaging.models.get_thumb_name)),
            ],
            bases=(models.Model, messaging.utils.IDSigner),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('thread_id', models.CharField(max_length=27, unique=True)),
            ],
            bases=(models.Model, messaging.utils.IDSigner),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('post', models.TextField(max_length=10000)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.Media')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.Thread')),
            ],
        ),
    ]
