# Generated by Django 2.2.4 on 2019-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20191117_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
