# Generated by Django 2.2 on 2019-08-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20190421_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='poster_id',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='password',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='password_enabled',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='token',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
    ]
