# Generated by Django 3.0.3 on 2020-04-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_thread_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['pk']},
        ),
    ]
